Repository kellyfabiolafc/start-boostrap-react, pull requests merged in 2023-07, with the labels that each got.

#5 advance section main...
  index.html
  src/App.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Main.jsx
  src/components/Navbar.jsx
  src/components/foot-parts/About.jsx
  src/components/foot-parts/Around.jsx
  src/components/foot-parts/Copyright.jsx
  src/components/foot-parts/FooterContainer.jsx
  src/components/foot-parts/Location.jsx
  src/components/foot-parts/index.js
  src/components/index.js
  src/components/sections/SectionMain.jsx
  src/components/sections/index.js
  src/css-modules/Footer.modules.css
  src/css-modules/Header.module.css
  src/css-modules/SectionMain.module.css
  src/css/globals.css
  src/index.css
Labels: enhancement, good first issue

#8 practicas con los componentes
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/Button.jsx
  src/components/Navbar.jsx
  src/components/index.js
  src/helpers/button.js
  src/index.css
Labels: good first issue

#10 add container component
  src/components/Container.jsx
  src/components/Navbar.jsx
  src/components/index.js
  src/components/sections/SectionMain.jsx
  src/css-modules/Footers.module.css
  src/index.css
Labels: enhancement

#13 header advance
  package.json
  pnpm-lock.yaml
  src/components/Container.jsx
  src/css-modules/Header.module.css
Labels: enhancement

#14 Feature sections
  src/App.jsx
  src/components/Container.jsx
  src/components/IconStarts.jsx
  src/components/Title.jsx
  src/components/index.js
  src/components/sections/SectionAbout.jsx
  src/components/sections/SectionContact.jsx
  src/components/sections/SectionPortfolio.jsx
  src/components/sections/index.js
  src/css-modules/Header.module.css
  src/css-modules/IconStart.module.css
  src/css-modules/SectionAbout.module.css
  src/css-modules/SectionContact.module.css
  src/css-modules/SectionPortfolio.module.css
Labels: question

#15 add scroll-behavior css in html
  src/components/sections/SectionPortfolio.jsx
  src/index.css
Labels: enhancement

#16 Feature sections
  src/components/sections/SectionAbout.jsx
  src/components/sections/SectionPortfolio.jsx
  src/css-modules/SectionAbout.module.css
  src/css-modules/SectionPortfolio.module.css
  src/index.css
Labels: enhancement

#18 END CHANGES
  src/css-modules/Footers.module.css
  src/css-modules/SectionAbout.module.css
  src/css-modules/SectionContact.module.css
Labels: enhancement
